### ISSUE TITLE
Can't make removeBehavior to work

### ISSUE THREAD

**Issue by Dazzid** [hapticdata/toxiclibsjs#34]
Hi 
I'm trying to removeBehavior of a particle but don't find the way to call the function properly.
physics.removeBehavior(this.AttractionBehavior());

How can I find this Attractor? 
Thanks for the help
David

**Comment by Dazzid** [comment]
Oh my fault I have found my mistake. After doing this:
var myAttraction = new AttractionBehavior(this, range, strength, 0.0001);
physics.addBehavior(myAttraction);
and then 
physics.removeBehavior(myAttraction);

**Comment by hapticdata** [comment]
glad you figured it out! thanks for reporting back
