### ISSUE TITLE
3D non-triangle geometry?

### ISSUE THREAD

**Issue by huttarl** [hapticdata/toxiclibsjs#35]
Hello,
Seeing the title and examples, I was hoping this library would support operatings on 3D geometry such as polyhedra. I'm excited to see that operations like subdivision are supported.
However, it seems that the only kind of 3D polygons supported are triangles.
Is there any plan to support meshes (surfaces) with squares, pentagons, or n-gons in general?

Thanks...

**Comment by hapticdata** [comment]
Hi @huttarl any 3d objects converted to a mesh will result in a `toxi.geom.mesh.TriangleMesh` or a `toxi.geom.mesh.WETriangleMesh` _(Winged Edge)_. There aren't any plans to expand into quads, pentagons etc.
