### ISSUE TITLE
Import/export from STL?

### ISSUE THREAD

**Issue by aatishb** [hapticdata/toxiclibsjs#36]
Hi, I was wondering if importing and exporting to STL are supported in toxiclibs.js?
Thanks!

**Comment by aatishb** [comment]
Alternatively if any other polygonal mesh file format is supported, that would be work for me as well. Thanks.

**Comment by hapticdata** [comment]
as of now STL import/export is not available. All meshes in toxiclibs.js are composed of triangular faces.

**Comment by aatishb** [comment]
hmm.. so is there any way to import or export a mesh (even one with triangular faces)? What I'm trying to do is import a 2D mesh into toxiclibs / P5, and then access the nodes and edges (so I can make it a hanging cloth with particles and springs, for example). My best guess right now is to save the mesh design to a SVG file and use a library to import that.

**Comment by hapticdata** [comment]
you can export a `toxi.geom.mesh.TriangleMesh` to OBJ using `toxi.geom.mesh.OBJWriter` here is a quick example from the [test](https://github.com/hapticdata/toxiclibsjs/blob/16631592649cf02a2d2a07bbb5577364c54f3c8d/test/geom.mesh.OBJWriter.js#L7-L9):

```js
var name = "myMesh";
var objWriter = new toxi.geom.mesh.OBJWriter(name +"-"+ new Date().getTime());
mesh.saveAsOBJ( objWriter );
//this returns the obj data as a String
var objBody = objWriter.getOutput();
```

this will give you a string that is a valid OBJ file, you will still need to write the file / or copy it from console to a file in your text editor.

OBJ files can't be imported back into toxiclibs.js but they can be imported into webgl environments such as [three.js](http://threejs.org).
