### ISSUE TITLE
Typescript typing

### ISSUE THREAD

**Issue by nkint** [hapticdata/toxiclibsjs#37]
Have you ever thought to add typing for Typescript?

**Comment by hapticdata** [comment]
There are some benefits for a library such as this but most of the code was written before Typescript had been announced. It would be a large undertaking at this point to modify the codebase to Typescript. I would encourage anyone wanting to do so to go ahead, I'd be curious to see it.

The code in this repository aims instead to be very _vanilla_ for javascript, its plain-ness is a strength. I do also try to handle things in a very natural javascript way, for example there are no `instanceof` tests anywhere, _types_ aren't the concern, instead its whether the object has the properties required of it to complete the operation.
